backend:
  name: git-gateway
  branch: master
local_backend: true # For local testing
media_folder: "images/uploads" # Where images are stored
public_folder: "/images/uploads"
collections:
  - name: "services"
    label: "Services"
    folder: "content/services"
    create: true
    slug: "{{day}}-{{month}}-{{year}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "description", label: "Description", widget: "text" }
      - { name: "image", label: "Image", widget: "image" }